version: '3.8'                    
services:                         
  postgres:                       
    image: postgres:17-alpine     
    container_name: eventhub-db   
    environment:                  
      POSTGRES_USER: eventhub     
      POSTGRES_PASSWORD: eventhub 
      POSTGRES_DB: eventhub       
    ports:                        
      - "5432:5432"              
    volumes:                      
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eventhub-network          

volumes:                          
  postgres_data:                  

networks:                         
  eventhub-network:
    driver: bridge