spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventhub
    username: eventhub
    password: eventhub
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api

app:
  jwt:
    secret: "7d4f8c9a1b2e3f4061728394a5b6c7d8e9f0123456789abcdef0123456789abcd"
    expiration: 3600000
    refreshTokenExpiration: 86400000
